# Generated by Django 4.1.7 on 2023-03-28 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='followers',
            new_name='follower',
        ),
    ]
