# Generated by Django 4.1.7 on 2023-05-02 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_review'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='thread',
            name='first_person',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='second_person',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
